#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound} ************************* 自定义配置 *************************
${symbol_pound} *** 应用打包类型 ***
application.env: 2
${symbol_pound} *** log自定义配置 ***
log:
  home: "/data/logs/${parentArtifactId}"
  level: "debug"
${symbol_pound} *** logback自定义配置 ***
spring.logback:
  access.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  error.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  info.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  application.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  sql.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  console.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level %logger{64}.%method:%line - %msg%n"
  history.suffix: ".log"

${symbol_pound} ************************* 第三方配置 *************************
${symbol_pound} *** datasource配置 ***
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&amp;failOverReadOnly=false&amp;maxReconnects=10&amp;characterEncoding=UTF8&amp;allowMultiQueries=true"
${symbol_pound}    url: "jdbc:log4jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&amp;failOverReadOnly=false&amp;maxReconnects=10&amp;characterEncoding=UTF8&amp;allowMultiQueries=true"
    username: "root"
    password: "tiger"
  redis:
    # Redis数据库索引（默认为0）
    ${symbol_pound} database: 0
    # rediss 表示使用ssl，@前面是用户信息，用户名和密码用 : 分割，@之后是服务器信息，ip和端口号用 : 分割
    ${symbol_pound} url: "redis://:password@127.0.0.1:6379"
${symbol_pound} 日志格式中 clr 占位符生效配置
  output.ansi.enabled: "NEVER"
  jmx:
#    jmx 是否开启
    enabled: false
  http:
#      是否开启上传文件
    multipart:
      enabled: false
  mvc:
    formcontent:
#      是否接收 put 请求
      putfilter:
        enabled: false
  autoconfigure:
      exclude:
        - "org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration"
        - "org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration"
        - "org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration"
        - "org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration"
${symbol_pound}        - "org.springframework.boot.autoconfigure.web.GsonHttpMessageConvertersConfiguration"
        - "org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration"
        - "org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration"
${symbol_pound}        - "org.springframework.boot.autoconfigure.cache.SimpleCacheConfiguration"
${symbol_pound}        - "org.springframework.boot.autoconfigure.cache.RedisCacheConfiguration"
${symbol_pound}        - "org.springframework.boot.autoconfigure.cache.NoOpCacheConfiguration"
${symbol_pound}        - "org.springframework.boot.autoconfigure.cache.GenericCacheConfiguration"