log:
  home: /data/logs/${parentArtifactId}
  level: info
spring:
  datasource:
    url: jdbc:mysql://111.1.57.148:3306/tc?autoReconnect=true&amp;failOverReadOnly=false&amp;maxReconnects=10&amp;characterEncoding=UTF8&amp;allowMultiQueries=true
    username: root
    password: kYCAxx6s9qe90HWnIPxWMQ
logback:
  access.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n
  error.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n
  info.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n
  application.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n
  sql.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n
  console.pattern: %d{yyyy-MM-dd HH:mm:ss.SSS} - [%thread] %-5level - %logger{35} - %msg%n